filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.labels.co.elastic.logs/enabled: "true"
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
              fields:
                service: "${data.docker.container.labels.com.docker.compose.service}"
                project: "netmgmt-suite"
              fields_under_root: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_host_metadata:
      when.not.contains.tags: forwarded

output.logstash:
  hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]
  compression_level: 3
  bulk_max_size: 1024

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
