filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
        match_fields: ["container.id"]
        match_pids: ["process.pid"]

output.logstash:
  hosts: ["192.168.5.13:5044"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded

